# Generated by Django 5.0.3 on 2024-03-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcelink',
            name='is_active',
        ),
    ]
